config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get 'wall/index'
  get 'profile/:id' => 'profile#show', as: 'profile'

  resources :repositories

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    post 'users/sync_repositories'
    authenticated :user do
      root to: 'wall#index', as: :wall
    end

    unauthenticated do
      root to: 'home#index'
    end
  end

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :pull_request

  scope :completed, -> { where.not(status: nil) }
  scope :running, -> { where(status: nil) }

  def elapsed_time
    ElapsedTime.new(started_at, finished_at) if completed?
  end

  def completed?
    status and finished_at
  end
end

app/models/concerns/elapsed_time.rb
class ElapsedTime
  extend ActiveSupport::Concern
  attr_reader :started_at, :finished_at, :diff

  def initialize(started_at, finished_at)
    @started_at = started_at
    @finished_at = finished_at
    @diff = Time.zone.at(@finished_at - @started_at)
  end

  def days
    @diff.day-1
  end

  def hours
    @diff.hour
  end

  def minutes
    @diff.min
  end

  def seconds
    @diff.sec
  end

  def to_s
    elapsed_time_string = [
      "#{days} days",
      "#{hours} hours",
      "#{minutes} minutes",
      "#{seconds} seconds"
    ]

    elapsed_time_string.select { |s| !s.starts_with? "0" }.join(", ")
  end

end

app/models/concerns/repository_sync.rb
class RepositorySync
  extend ActiveSupport::Concern

  def self.fake_sync(user)
    user.repositories.destroy_all
    FactoryGirl.create_list(:repository, 10, user: user)
    user.repositories.reload
    repository = user.repositories.where(active: true).first
    FactoryGirl.create_list(:pull_request, 8, repository: repository)
    FactoryGirl.create(:build, pull_request: repository.pull_requests.sample)
  end

end

app/models/host.rb
class Host < ActiveRecord::Base
    has_many :repositories
    validates_presence_of :url, :docker_port, :docker_protocol

    enum docker_protocol: { http: "http", https: "https"}
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :repository
  has_many :builds, :dependent => :delete_all
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
  has_many :pull_requests, dependent: :destroy
  has_many :builds, through: :pull_requests, dependent: :destroy
  validates_presence_of :user, :name, :provider, :url

  def builds_running
     builds.running
  end

  def build_history
    builds.completed
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable, :omniauth_providers => [:bitbucket]

  friendly_id :name, use: :slugged

  has_many :repositories

  def username
    name || email
  end

  def avatar_url
    gravatar_id = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def sync_repositories
    RepositorySync.fake_sync(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push  :name, :slug
    devise_parameter_sanitizer.for(:account_update).push  :name, :slug
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def bitbucket
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "bitbucket") if is_navigational_format?
    else
      session["devise.bitbucket_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_respository, only: [:show, :update]

  def show
    @hosts = Host.all
  end

  def update
    @repository.host = Host.find params[:repository][:host_id]
    @repository.active = params[:repository][:active]
    @repository.save
    redirect_to repository_path
  end

  private
  def set_respository
    @repository = current_user.repositories.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sync_repositories
    current_user.sync_repositories
    redirect_to repository_path(current_user.repositories.first)
  end

end

app/controllers/wall_controller.rb
class WallController < ApplicationController
  def index
    @repositories = current_user.repositories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, size=48)
    "#{user.avatar_url}?s=#{size}&d=mm"
  end

  def current_user?(user)
    user and user.id == current_user.id
  end
end

app/helpers/wall_helper.rb
module WallHelper
end

app/views/builds/_list.html.erb
<% builds.each do |build| %>
  <strong>#<%= build.id %></strong>:
  <%= build.status %>
  <%= build.started_at.to_formatted_s(:db) %> - <%= build.elapsed_time %>

<% end %>

app/views/containers/_list.html.erb
<h1>Containers</h1>
<p>show running containers</p>

app/views/home/index.html.erb
<h1>TerryCI</h1>
<p>take your existent pipe line and let us take care your production branche</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TerryCi</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TerryCI</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <a href="#" data-target="menu" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %>
              <img class="img-circle" src="<%= current_user.avatar_url %>" alt="<%= current_user.email %>" width="24">
              <span class="caret"></span>
            </a>
            <ul id="menu" class="dropdown-menu">
            <li>
              <%= link_to "Profile", profile_path(current_user) %>
            </li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path(), method: 'DELETE' %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign in with Bitbucket", user_omniauth_authorize_path(:bitbucket) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <%= yield %>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
</body>
</html>

app/views/pull-requests/_list.html.erb
<h1>Pull Requests</h1>

<% pull_requests.each do |pull_request| %>
  <p> <%= image_tag avatar(pull_request.user, 26), class: "img-circle" %>  <%= pull_request.user.name %> - <%= pull_request.title %></p>
<% end %>

app/views/repositories/_list.html.erb
<h2>Repositories

  <%= link_to users_sync_repositories_path, method: "POST", class: "btn btn-success pull-right" do %>
    <i class="fa fa-refresh"></i>
    Sync
  <% end %>
</h2>

<ul class="list-group" >
<% repositories.each do |repository|  %>
<li class="list-group-item">
  <%= fa_stacked_icon repository.provider+" ", base: 'circle-thin' %>
  <input type="checkbox" <%= 'checked' if repository.active %> data-toggle="toggle" data-onstyle="success">
  <%= link_to repository.name, repository %>
  <a href="#" class="pull-right">
    <%= fa_icon 'gear' %>
  </a>
</li>
<% end %>
</ul>

app/views/repositories/_settings.html.erb
<%= form_for @repository do |f| %>
<h1>Settings
  <div class = "pull-right"><%= f.check_box :active, :checked => @repository.active, :data => { :toggle => "toggle", :onstyle => "success" } %> </div>
</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Host</h3>
  </div>
  <div class="panel-body">
     <%= f.select :host_id, @hosts.collect {|host| [ host.url, host.id] } ,{}, { :class =>  "form-control"} %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Docker Config</h3>
  </div>
  <div class="input-group panel-body">
    <span class="input-group-addon" id="docker_user">User</span>
    <input type="text" class="form-control" placeholder="Username" aria-describedby="docker_user">
  </div>
  <div class="input-group panel-body">
    <span class="input-group-addon" id="docker_password">Password</span>
    <input type="password" class="form-control" placeholder="Password" aria-describedby="docker_password">
  </div>
  <div class="input-group panel-body">
    <span class="input-group-addon" id="basic-addon1">Docker Images</span>
    <select class="form-control" placeholder="Password" >
      <option value="volvo">bluesoftbr/erp</option>
      <option value="volvo">bluesoftbr/acelerato</option>
    </select>
  </div>
</div>
<div class="form-group pull-right">
  <%= f.submit "Save" , :class => "btn btn-default" %>
</div>
<% end %>

app/views/repositories/show.html.erb
<div class="col-md-4">
  <%= render "/repositories/list", repositories: current_user.repositories %>
</div>

<div id="repository" class="col-md-8">

  <% unless @repository.active %>
      <div class="alert alert-warning">
        <i class="fa fa-exclamation-triangle"></i>
        This repository is not activated!
      </div>
  <% end %>

  <h1><%= fa_stacked_icon @repository.provider+" inverse", base: 'circle' %><%= @repository.name %></h1>
  
  
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#current" aria-controls="current" role="tab" data-toggle="tab">Current</a>
    </li>
    <li role="presentation">
      <a href="#pull-requests" aria-controls="pull-requests" role="tab" data-toggle="tab">Pull Requests</a>
    </li>
    <li role="presentation">
      <a href="#build-history" aria-controls="build-history" role="tab" data-toggle="tab">Build History</a>
    </li>
    <li role="presentation">
      <a href="#containers" aria-controls="containers" role="tab" data-toggle="tab">Containers</a>
    </li>
    <li role="presentation">
      <a href="#settings" aria-controls="containers" role="tab" data-toggle="tab">Settings</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="current">
      <h1>Current</h1>
      <p>show builds running</p>
    </div>
    <div role="tabpanel" class="tab-pane" id="pull-requests">
      <%= render "/pull-requests/list" %>
    </div>
    <div role="tabpanel" class="tab-pane" id="build-history">
      <%= render "/builds/list" %>
    </div>
    <div role="tabpanel" class="tab-pane" id="containers">
      <%= render "/containers/list" %>
    </div>
    <div role="tabpanel" class="tab-pane" id="settings">
      <%= render :partial => "/repositories/settings" %>
    </div>
  </div>
</div>

app/views/wall/index.html.erb
<%= render "/repositories/list", repositories: @repositories %>